### PR TITLE
Some improvements: second try

### PR DESCRIPTION
**Pull request by exweilt**
this time added some background to console, reduced its size a bit(it was probably huge to you because you launched the engine as dll with auto resolution, while I used to launch as executable(forgot about dll :p ).
In exe it is still quite compact).

### CODE REVIEW

**Comment by vladislavrv** [comment]
well done!
please do not forget to test DLL mode too as this is the main target mode (we don't want to break backward compatibility).
once this PR will be approved github will start an automated build which will result in two DLLs - one built with MSVC, and other from GCC. please download and test them both at least briefly to make sure both options are still working fine with your changes.
then feel free to click "merge" (no squash, no fast-forward). probably i'll have to put this manual to readme one day...
also, you don't have to close old pull request and start a new one just to fix something, you know? just push new commits to your branch, github knows what to do with it.
and if you'll have any questions don't hesitate to ask me ;)

**Comment by exweilt** [comment]
@vladislavrv,
MSVC is fine, while there is no even option to start a Planetary Battle game(from main menu) with GCC artifact.
I downloaded gcc dll from previous pull request and it doesnt work too, so it's not due to the changes.

**Comment by exweilt** [comment]
B.T.W. I have no [write access](https://docs.github.com/articles/what-are-the-different-access-permissions), so I can't merge

**Comment by vladislavrv** [comment]
> @vladislavrv, MSVC is fine, while there is no even option to start a Planetary Battle game(from main menu) with GCC artifact. I downloaded gcc dll from previous pull request and it doesnt work too, so it's not due to the changes.

hmm, looks like it wants you to have exact the same gcc libs to be "installed". Solvable i guess, will take a closer look once have some time for it. As a "workaround" you can download [this bundle](https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.2-11.0.0-ucrt-r1/winlibs-i686-mcf-dwarf-gcc-13.1.0-mingw-w64ucrt-11.0.0-r1.7z) and put it into your PATH env var.

> B.T.W. I have no [write access](https://docs.github.com/articles/what-are-the-different-access-permissions), so I can't merge

Also gonna check what i can do with it later.

**Comment by exweilt** [comment]
Now it works.
You have very good intuition!

**Pull request merged**
