### PR TITLE
Use Unicode for system path

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes game startup for exe build

### CODE REVIEW

**Comment by vladislavrv** [comment]
Hey,
nicely done!
Just one question - i guess it was not working for you in some specific environment (cyrillic symbols in the path or something), right? Could you please then briefly describe the problem this fix is solving in the merge commit message, so this info will not be lost?
Thanks :)

**Review by vladislavrv — APPROVED** [review]

**Comment by TheNormalnij** [comment]
Yeah.
I use Windows 10 Home Single language. So by default it uses `C:\Users\%USERNAME%\OneDrive\Документы\SpaceRangersHD` as SR2 documents folder. 

Regression:
Exe build crashes when it trying to save minimap in folder with not ascii characters.

Fix:
Force use UTF WinAPI for affected calls.

Regression potential:
Cache doesn't works
Screenshots doesn't works
Crash logs doesn't works (?) // Im not so sure.  I didn't test it

Tested on DLL and EXE builds.

Possible additional refactor:
Define UNICODE for whole project.

**Comment by TheNormalnij** [comment]
Maybe, project can use <tchar.h> for strings. But there is a lot of char -> wchar casts.

**Comment by vladislavrv** [comment]
> Maybe, project can use <tchar.h> for strings

I'd say we should prefer standard classes over any non-standard or custom solutions.
Actually `std::string` nowadays is totally able to manage unicode, so the only question is to WinAPI - why is it still so stupid.
Let's just stick to `wstring` thing for now, it's widely used in the project anyway.

**Pull request merged**
